force periscopic version 2.0.1
periscopic 2.0.2 is causing errors in code-red:
TypeError: Cannot read property 'find_owner' of undefined

https://github.com/sveltejs/svelte/issues/5358